### ISSUE TITLE
Authentication to mongoDB

### ISSUE THREAD

**Issue by DareBoost** [alexanderjarvis/play-jongo#22]
I have recently installed this plugin and I would like to use mongoDB authentication abilities.

I tried to put user and password as URI in the configuration file : 
playjongo.uri="mongodb://user:pwd@127.0.0.1:27017/dbname"

all I get is : 
play.api.Application$$anon$1: Execution exception[[MongoException: unauthorized db:play ns:play.pages lock type:0 client:127.0.0.1]]

However it works with mongo client : 
$ mongo
MongoDB shell version: 2.2.4
connecting to: test
> use dbname
switched to db dbname
> db.auth("user", "pwd")
1
 
Any idea ?

**Comment by magro** [comment]
@DareBoost Please try to get this to work with plain jongo at first. Once you figured out how it works with jongo it should be clearer what has to be done in this plugin (if anything at all).
