### ISSUE TITLE
Add support for multiple playjongo.uri in application.conf

### ISSUE THREAD

**Issue by mingfang** [alexanderjarvis/play-jongo#28]
Currently play-jongo only support one playjongo.uri and is used by the static PlayJongo.getInstance(). 

It would be better to allow multiple playjongo.uri just like Play's db support.  The pattern would be playjongo.default.uri for the default and playjongo.mydb.uri.

At the code level, PlayJongo.getInstance() would return playjongo.default.uri.
PlayJongo.getInstance("mydb") would return playjongo.mydb.uri

**Comment by magro** [comment]
Timeout

**Comment by ananyashandilya1102** [comment]
I have a similar requirement as I wish to connect to two different databases from the same app. Is this possible? @magro

**Comment by magro** [comment]
It's possible via pull requests :-)
