### ISSUE TITLE
Update to jongo-1.2 and mongo-java-driver-2.13.1

### ISSUE THREAD

**Issue by theranger** [alexanderjarvis/play-jongo#35]
Hi,

Time has gone by and both Jongo and MongoDB Java driver has moved on. Can you please update your project as well?

**Comment by alexanderjarvis** [comment]
PR welcome. I no longer maintain this project.

**Comment by theranger** [comment]
Oh, okey. I would make the modifications by myself. Can you give me a write access to the repo or do you prefer forking?

**Comment by magro** [comment]
@theranger If you send a pull request I can make a release. Another one maintaining this project would be fine as well if course.

**Comment by magro** [comment]
@theranger Do you need to jongo update for play 2.3 oder 2.4? The new version 0.8.0-jongo1.2 is built for play 2.4 and comes with an updated version of jongo.

**Comment by theranger** [comment]
I am currently on 2.3, but planning an update to 2.4 in the near future anyway.
So for me 0.8.0-jongo1.2 for 2.4 is perfectly fine. Thank you!

**Comment by magro** [comment]
Great!
