### ISSUE TITLE
Jongo support for SCRAM-SHA-1 auth ?

### ISSUE THREAD

**Issue by loicknuchel** [alexanderjarvis/play-jongo#41]
Hi,

Since mongo 3.0, there is a new authentication mode : SCRAM-SHA-1

Do Jongo support it ?
If yes, how to enable it ?

My problem: I use heroku with mongolab and the authentication method mode MUST be SCRAM-SHA-1.
My jongo uri seems correct but I get an auth error.
Any idea on how I can get this working ?

This issue may be related to https://github.com/alexanderjarvis/play-jongo/issues/22

PS: I'm using Play 2.3.4, mongo 3.0.7 & play-jongo 0.7.1-jongo1.0,

**Comment by magro** [comment]
@loicknuchel Please try to get this to work with plain jongo at first. Once you figured out how it works with jongo it should be clearer what has to be done in this plugin (if anything at all).
