### ISSUE TITLE
JongoModule: CreationException - Binding points to itself

### ISSUE THREAD

**Issue by sdk451** [alexanderjarvis/play-jongo#45]
Hi thanks for creating this.

I've just attempted to shift to the play Module implementation and I get this on run of my play project.

CreationException: Unable to create injector, see the following errors:

1) Binding points to itself.
  at uk.co.panaxiom.playjongo.JongoModule.bindings(JongoModule.java:16):
Binding(class uk.co.panaxiom.playjongo.PlayJongo to ConstructionTarget(class uk.co.panaxiom.playjongo.PlayJongo)) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

1 error

**Comment by sdk451** [comment]
the binding within the JongoModule doesn't follow the suggested pattern i.e -bind(PlayJongo.class).to(MyPlayJongoImplementation.class) - but I'm not familar enough with DI to code a fix

public class MyModule extends Module {
  public Seq<Binding<?>> bindings(Environment environment, Configuration configuration) {
    return seq(
      bind(MyComponent.class).to(**_MyComponentImpl.class_**)
    );

**Comment by magro** [comment]
@sdk451 Thanx for the pointer, the fix is with version 1.0.1-jongo1.2 on its way to maven central.
