### ISSUE TITLE
github repo tagline is confusing/misleading

### ISSUE THREAD

**Issue by matanster** [alexanderjarvis/play-jongo#46]
It currently says version 2.2 of Play
> Play 2.2 Module for Jongo

**Comment by magro** [comment]
@matanster You're right, unfortunately I don't have the required permissions do change that.

@alexanderjarvis Can you change the project description to s.th. like "Play Module for Jongo http://jongo.org/" or give me the required permissions/role to change that?

**Comment by alexanderjarvis** [comment]
Done! I don't think it's possible to adjust permissions for that.

**Comment by magro** [comment]
Thanks @alexanderjarvis!
