### ISSUE TITLE
Play 2.5

### ISSUE THREAD

**Issue by morellik** [alexanderjarvis/play-jongo#48]
Did you try play-jongo on Play 2.5? Is there a way to use under Play 2.5?

**Comment by magro** [comment]
It should be possible to use it with play 2.4/2.5, this was done with #44. If it doesn't work this issue is valid :-)

**Comment by morellik** [comment]
Using the following libraries in build.sbt
 "org.mongodb" % "mongo-java-driver" % "3.2.2",
  "org.jongo" % "jongo" % "1.2",
  "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.4.1" % "optional",
  "uk.co.panaxiom" %% "play-jongo" % "1.0.1-jongo1.2"

I receive the following warning:

[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.typesafe.play:play-netty-server_2.11:2.4.2 -> 2.5.0 (caller: docarchive:docarchive_2.11:1.0-SNAPSHOT, uk.co.panaxiom:play-jongo_2.11:1.0.1-jongo1.2)
[warn] 	* com.typesafe.play:play-java_2.11:2.4.2 -> 2.5.0 (caller: com.typesafe.play:filters-helpers_2.11:2.5.0, docarchive:docarchive_2.11:1.0-SNAPSHOT, com.typesafe.play:play-java-jdbc_2.11:2.5.0, uk.co.panaxiom:play-jongo_2.11:1.0.1-jongo1.2, com.typesafe.play:play-java-ws_2.11:2.5.0)
[warn] 	* com.typesafe.play:play-server_2.11:2.4.2 -> 2.5.0 (caller: com.typesafe.play:play-netty-server_2.11:2.5.0, docarchive:docarchive_2.11:1.0-SNAPSHOT, uk.co.panaxiom:play-jongo_2.11:1.0.1-jongo1.2)

**Comment by mancvso** [comment]
jackson-module-scala says on this Github page
```
Please use versions 2.6.5, or 2.7.2; earlier released versions are known to contain significant bugs.
```

**Comment by magro** [comment]
I'd say that you can ignore the warnings, or exclude transitive dependencies where needed.

**Comment by morellik** [comment]
If I've to write a production application I prefer to have compatibility libraries. In this case the Play! evicts the incompatibility libraries so I don't know how to use them.
Another issue regards the application.conf that was changed and I don't know where put the database declaration.

**Comment by morellik** [comment]
One of the Play! contributors told me: "The migration for Play modules is not as much as it was in 2.4, so it should not be too difficult for library authors to update." 

So, if you can, we are happy!

Thanks

**Comment by magro** [comment]
I'm going to vacation tomorrow, not sure about my workload afterwards. If you submit a pull request I can make a release then.

**Comment by morellik** [comment]
I tried, but github ask me to compare branches and I didn't know what I've to do. I'll wait until you come back from you vacation.

Good vacation ;-))

**Comment by magro** [comment]
Github has rather good docs... :-) Thanks!

**Comment by morellik** [comment]
I checked the Play! module documentation and the jongo sources and I don't understand where is the incompatibility, You follow exactly the documentation guidelines.

**Comment by morellik** [comment]
The only different thing is that in your JongoModule.java you use @Override while in the documentation there isn't.

**Comment by morellik** [comment]
The group answer is: Modules don't exist anymore in 2.5. A "module" in 2.5 is just a bunch of classes that are bound in DI.

**Comment by magro** [comment]
Right, so what's the problem? Just register the JongoModule.

**Comment by morellik** [comment]
;-))) How?

I tried to put 
play.modules {
  enabled += uk.co.panaxiom.playjongo.JongoModule
}

in application.conf, but PlayJongo continues to be evicted by Play.

**Comment by morellik** [comment]
Another Play Group answer: Looks like it depends on Play 2.4, which isn't compatible with 2.5 on a binary level.

**Comment by gmethvin** [comment]
@magro If it works for 2.5, can you create a release that is compiled against 2.5, to ensure binary compatibility?

**Comment by morellik** [comment]
Recompiling using Play 2.5 libraries, all seems to works fine.

**Comment by morellik** [comment]
I spoke too soon. All works fine on IntelliJ importing the recompiled PlayJongo by hand. But when Play compiles the sources it not find PlayJongo and stops with compilation errors.
So like  gmethvin ask, please recompile PlayJongo against Play 2.5.

**Comment by morellik** [comment]
Is it possible release a version compiled against 2.5?

**Comment by ShahBinoy** [comment]
Submitted a PR for it #53

**Comment by morellik** [comment]
Thanks

**Comment by magro** [comment]
@ShahBinoy Thanks a lot for the PR! I just released the change (with some other lib updates) as 2.0.0-jongo1.3, here's the [list of changes](https://github.com/alexanderjarvis/play-jongo/compare/f14be99...8562838). 

Please note that I didn't have time to battle test this in integration, if there's anything not working please submit an issue or update this one.

The [README/Usage documentation](https://github.com/alexanderjarvis/play-jongo#usage) also needs adjustments, it would be great if anybody could submit a PR - many thanks in advance!
