### ISSUE TITLE
Example customer jackson mapper for play-jongo

### ISSUE THREAD

**Issue by sdk451** [alexanderjarvis/play-jongo#49]
Could someone provide an example of how to add the jackson JodaMapper to the JongoScalaMapperFactory implemention of JongoMapperFactory?  Joda.DateTime variables cause unmarshalling exceptions unless one registers a JodaMapper() module to the jackson ObjectMapper(). the obvious hook for registering it is the JongoScalaMapperFactory, but I can't seem to figure how it can be done with this kind of builder pattern. I've had a look at both the jackson wiki and played around a bit with play-jongo but I can't crack it.

**Comment by sdk451** [comment]
Actually I just figured out - (never seen this .registerModule().registerModule() java syntax before)

package modules;

import org.jongo.Mapper;
import org.jongo.marshall.jackson.JacksonMapper;

import com.fasterxml.jackson.module.scala.*;
import com.fasterxml.jackson.datatype.joda.*;

/**
 * Creates a mapper that handles marshalling of scala and joda types
 */

public class JongoScalaMapperFactory implements JongoMapperFactory {

    @Override
    public Mapper create() 
    {
        return new JacksonMapper.Builder().registerModule(new DefaultScalaModule()).registerModule(new JodaModule()).build();
    }

}

**Comment by magro** [comment]
Great that you solved it!
