### ISSUE TITLE
Using the module in a stand alone.

### ISSUE THREAD

**Issue by chrisp22** [alexanderjarvis/play-jongo#54]
I wanted to use these module in my SBT stand alone module to save data and manipulate it.

**Comment by magro** [comment]
Can you please be a bit more specific on what you want to achieve and what's the actual issue?

**Comment by chrisp22** [comment]
i have an SBT project that is Not play framework, but it has the play
framework architecture. of resent  i managed to add ebean for mysql to it.
I found that Mongodb would solve the database reads and write that i am
facing. I want to replace the Mysql Ebean with Mongodb. Looking at
play-jongo, just like play-ebean, i can add it to the Stand alone SBT
project and use it.

The problem is that i don't know how to add it and if it can work without
play framework plugin. My application is a Java jar.






*Regards, *

CTO and Dev, creativeDNA  (U) LTD. <http://www.creativedna.co.ug/>

@Google Plus <https://plus.google.com/+ChrispinusOnyancha>
@LinkedIn <http://ug.linkedin.com/in/ChrispinusOnyancha>
@Tweeter <https://twitter.com/Chrisp_onyanx>

<https://play.google.com/store/apps/details?id=com.creativeDNA.ntvuganda&rdid=com.creativeDNA.ntvuganda&rdot=1&feature=md>

**Comment by magro** [comment]
This plugin is built for / tied to play, so you cannot use it without play. For you it would be easier to use a Mongo client or jongo directly. Cheers

**Comment by chrisp22** [comment]
Thanks for the feed back
