### ISSUE TITLE
Problem with Jongo Library in Play 2.5

### ISSUE THREAD

**Issue by ccsalazarr-commercetools** [alexanderjarvis/play-jongo#55]
I have added this to the build.sbt

libraryDependencies ++= Seq(
  "uk.co.panaxiom" %% "play-jongo" % "2.0.0-jongo1.3"
)

but the library is not downloaded and I cannot create any instance of PlayJongo, any idea?

**Comment by chekurisriharsha** [comment]
Use "uk.co.panaxiom" % "play-jongo_2.11" % "2.0.0-jongo1.3" instead. Found this on https://mvnrepository.com/artifact/uk.co.panaxiom/play-jongo_2.11/2.0.0-jongo1.3

**Comment by magro** [comment]
The double percent in `"uk.co.panaxiom" %% "play-jongo" % "2.0.0-jongo1.3"` should actually take care of this.

**Comment by ShahBinoy** [comment]
@chekurisriharsha please close the issue if resolved

**Comment by chekurisriharsha** [comment]
@ShahBinoy For some reason `%%` was not working in my machine.

 I don't see close option. Sorry github newbie here. Please feel free to close if it works for you.

**Comment by magro** [comment]
Closing this issue, please reopen if it's still relevant.
