### ISSUE TITLE
How to specify an ObjecId as route parameter?

### ISSUE THREAD

**Issue by jeep87c** [alexanderjarvis/play-jongo#59]
How do I get the following route working:

GET        /:id        com.foo.FooController.getFoo(id: org.bson.types.ObjectId)

I'm getting the following error:
No URL path binder found for type org.bson.types.ObjectId. Try to implement an implicit PathBindable for this type.

I could obviously write my own ObjectId that would be a simple wrapper above org.bson.types.ObjectId but would also implement PathBindable. But I'm curious if there's a working and simple solution already out there (found something using play-salat but looks like it's not working with 2.11.8 scala version yet).

Another solution would be to change this parameter to a String instead of ObjectId but by doing that I'll have to manually map the string value to a ObjectId and support exceptions.

What do you think?

**Comment by magro** [comment]
This could help:http://cjwebb.github.io/blog/2015/06/23/play-framework-path-binders/

Can we close this issue?

**Comment by jeep87c** [comment]
You're right. The only way to get this working is to create my own binder. I'll see what I come with after my vacation.

Thanks for your reply!
