### ISSUE TITLE
How to use PlayJongo from static context? 

### ISSUE THREAD

**Issue by jorexe** [alexanderjarvis/play-jongo#61]
Hi! i'm new using jongo on Play Framework 2.5 and i was trying to use it like in Play Framework 2.4, but PlayJongo class can't be used from a static method.

Cheers, Jorge

**Comment by morellik** [comment]
To use play-jongo with Play 2.5.x I create a folder named _repositories_ at the same level of controllers and models to obtain a structure like:

|-controllers
|- models
|- repositories

In models I've the collection structure, like:

```
public class Users {

    @JsonProperty("_id")
    private ObjectId _id;
    private String firstname;
    private String lastname;
    private String email;

```

In the repositories I've a class for each model containing the play-jongo injection, the MongoCollection and all operations I want to do with the collection:

```
public class UsersRepository {

    @Inject
    private PlayJongo jongo;

    private MongoCollection users() {
        return jongo.getCollection("DB.users");
    }

    public Users findByEmail(String email) {
        return users().findOne("{email: #}", email).as(Users.class);
    }
```

In the controller  I've to inject UsersRepository to obtain access to the collection methods:

```
import views.html.modifyUserView

public class User extends Controller {

    @Inject private UsersRepository users;

   @Security.Authenticated(Secured.class)
    public Result modifyUser(String email) {
        Users u = users.findByEmail(email);
        return ok(modifyUserView.render(u));
    }
```
I hope this help you.
