### ISSUE TITLE
Play 2.6 update

### ISSUE THREAD

**Issue by greenled** [alexanderjarvis/play-jongo#66]
Hi. Play 2.6 was released a few days ago. Please could you update play-jongo to work with Play 2.6? Regards, Juan Carlos

**Comment by magro** [comment]
Do you want to submit a pull request?

**Comment by greenled** [comment]
Sure! I'm working on it.

I updated the module to scala 1.12.x and replaced `play.Configuration` references with `com.typesafe.config.Config` as suggested in [the migration docs](https://www.playframework.com/documentation/2.6.x/JavaConfigMigration26).

The main difference is that, unlike `Configuration`, `Config` does not allow default values when querying a configuration value, so [defaults should always be defined](https://www.playframework.com/documentation/2.6.x/JavaConfigMigration26#config-values-should-always-be-defined).

BTW, I would also like to update `jackson-module-scala` and `mongo-java-driver` dependencies. Should I open a new issue for this or just do it in several commits as part of the update?

**Comment by brainztorm** [comment]
Thanks ! :)

**Comment by greenled** [comment]
Module version has not been updated yet BTW

**Comment by magro** [comment]
Updating deps in the same PR is fine for me.
