### ISSUE TITLE
Play jongo with sbt 2.12.2

### ISSUE THREAD

**Issue by kavuri** [alexanderjarvis/play-jongo#68]
Does Jongo with sbt 2.12.2? Adding the following as dependency in build.sbt does not work

val appDependencies = Seq(
  "uk.co.panaxiom" %% "play-jongo" % "2.0.0-jongo1.3"
)

But if I change the version to 2.11, it works

**Comment by greenled** [comment]
AFAIK it doesn't: It's compiled for 2.11. See #67 #66 #62 for ongoing work upgrading to 2.12 and Play 2.6.x.

**Comment by kavuri** [comment]
@greenled But the README clearly mentions that Play 2.6.x is supported? Am I missing something?

**Comment by greenled** [comment]
Yeap, you are :). Sorry, I wasn't clear. The README is on the master branch, which is some commits ahead of the latest release. Play 2.6 **should** ship on next release. On the meantime you can build the module, publish it locally, and test it.

**Comment by kavuri** [comment]
@greenled thanks for the clarification. When is the next release planned? Any tentative date?

**Comment by greenled** [comment]
@kavuri No idea, I'm not a core developer. @magro @alexanderjarvis when is the next release planned?

**Comment by kavuri** [comment]
@magro @alexanderjarvis I am eagerly waiting for the next release to support Play 2.6.6. When is it planned?
If there is a snapshot version, how can I point my application to it?
Thanks

**Comment by greenled** [comment]
@magro @alexanderjarvis any clue on this?

**Comment by magro** [comment]
Sorry for the delay! I just released play-jongo 2.1.0-jongo1.3 which is now built with scala 2.12.

Thanks for you contributions and patience! ;-)
